version: '3.8'
services:
  nestjs-boilerplate:
    build: .
    env_file:
      - ./.env
    ports:
      - $APP_PORT:$APP_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    volumes:
      - .:/usr/src/app
    command: npm run start:debug:docker
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    stdin_open: true

volumes:
  db:
